# Generated by Django 5.0.7 on 2024-07-29 19:35

import text_to_game_ai.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(blank=True, upload_to=text_to_game_ai.models.file_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
